Repository MNGFinal/CafeSync-Back, pull requests merged in 2025-03, with the labels that each got.

#153 [25.02.28] 컴플레인 기본 조회 로직
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/ComplainController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/Entity/Complain.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/dao/ComplainRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/dto/ComplainDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/service/ComplainService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/dto/ScheduleDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/entity/Schedule.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#154 [25.03.02] 채팅 기능 구현
  CafeSync-FinalProject/build.gradle
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/Application.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/controller/ChatController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/controller/ChatPresenceController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/controller/ChatWebSocketController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/controller/ChatWebSocketHandler.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dao/ChatReadRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dao/ChatRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dao/ChatRoomParticipantRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dao/ChatRoomRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dto/ChatMessage.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dto/ChatRoomDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dto/ChatRoomParticipantDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dto/ChatRoomRequest.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dto/RoomType.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/entity/Chat.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/entity/ChatRead.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/entity/ChatRoom.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/entity/ChatRoomParticipant.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/service/ChatMessageService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/service/ChatPresenceService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/service/ChatReadService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/service/ChatRoomService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/service/ChatService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/CorsConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/RedisConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/RoomTypeConverter.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/WebSocketConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/EmpController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dao/EmpRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dto/EmployeeDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dto/FranChiseJoinDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dto/JobDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Employee.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Job.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/EmployeeService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#155 [25.03.04] basic -> main
  CafeSync-FinalProject/build.gradle
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/Application.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/controller/ChatController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/controller/ChatPresenceController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/controller/ChatWebSocketController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/controller/ChatWebSocketHandler.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dao/ChatReadRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dao/ChatRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dao/ChatRoomParticipantRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dao/ChatRoomRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dto/ChatMessage.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dto/ChatRoomDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dto/ChatRoomParticipantDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dto/ChatRoomRequest.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/dto/RoomType.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/entity/Chat.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/entity/ChatRead.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/entity/ChatRoom.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/entity/ChatRoomParticipant.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/service/ChatMessageService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/service/ChatPresenceService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/service/ChatReadService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/service/ChatRoomService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/model/service/ChatService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/ComplainController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/Entity/Complain.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/dao/ComplainRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/dto/ComplainDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/service/ComplainService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/CorsConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/RedisConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/RoomTypeConverter.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/WebSocketConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/EmpController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dao/EmpRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dto/EmployeeDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dto/FranChiseJoinDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dto/JobDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Employee.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Job.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/EmployeeService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/dto/ScheduleDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/entity/Schedule.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#158 [25.03.04] 공급업체 관리
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/controller/VendorController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/dto/VendorDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/entity/Vendor.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/service/VendorService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#161 [25.03.05] 본사 메뉴 관리 수정 및 단종 기능 추가
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/controller/MenuController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/dao/MenuRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/entity/Menu.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#163 [25.03.05] 본사 가맹점 관리 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/service/FranService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#164 Feature/160(컴플레인등록로직)
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/ComplainController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/service/ComplainService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/controller/MenuController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/dao/MenuRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/entity/Menu.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/controller/VendorController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/dto/VendorDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/entity/Vendor.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/service/VendorService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#170 [25.03.06] 가맹점 직원 관리
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/EmpController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dao/EmpRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Employee.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/EmployeeService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#168 [25.03.06] 공지사항 바리스타노트 정렬
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/service/FranService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/service/NoticeService.java
Labels: 🔙백엔드🔙

#171 [25.03.06] basic -> main
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/service/NoticeService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#173 [25.03.06] 가맹점 메뉴별 통계
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/controller/StatController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dao/StatRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/MenuSalesDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/entity/Stat.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/service/StatService.java
Labels: ✅PR(Pull Request)✅

#176 [25.03.06] 컴플레인 조회 로직 수정
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/ComplainController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/Entity/Complain.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/dao/ComplainRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/service/ComplainService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙, 🛠️수정🛠️

#177 [25.03.07] basic -> main
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/ComplainController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/Entity/Complain.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/dao/ComplainRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/service/ComplainService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#179 [25.03.07] 공지사항, 바리스타 노트 파일첨부 기능 추가
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/EmpController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/EmployeeService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/NoticeController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/service/NoticeService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#180 [25.03.07] 메인화면 데이터 표현하기
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/NoticeController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/entity/Notice.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/MonthlySalesDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/SalesDataDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/SalesSummaryDTO.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#185 [25.03.07] 일정 관리 조회 로직
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/ComplainController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/controller/PromotionController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/dao/PromotionRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/dto/PromotionDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/entity/Promotion.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/service/PromotionService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/service/a.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#188 [25.03.05] Basic -> Main
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/ComplainController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/controller/PromotionController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/dao/PromotionRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/dto/PromotionDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/entity/Promotion.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/service/PromotionService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/service/a.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#189 [25.03.08] 세금계산서 버그 수정
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/model/service/TaxService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#191 [25.03.08] 본사 발주내역 승인 반려 추가
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/OrderRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/inventory/model/dao/InventoryRepository.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#192 [25.03.08] 발주내역 내림차순
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java
Labels: ✅PR(Pull Request)✅

#194 [25.03.08] 토큰 갱신 기능 추가
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#196 [25.03.10] 발주 신청 성능 개선
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#197 [25.03.10] 성능 개선
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#199 [25.03.11] 본사통계추가
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/OrderRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/inventory/model/dao/InventoryRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/entity/Menu.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/controller/StatController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dao/StatRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/MenuSalesDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/MonthlySalesDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/StatDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/StoreSalesDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/TodaySalesDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/entity/Stat.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/service/StatService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/model/service/TaxService.java
  CafeSync-FinalProject/src/main/resources/application.yml
Labels: ✅PR(Pull Request)✅

#203 [25.03.12] 일정 등록, 수정, 삭제
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/controller/PromotionController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/dao/PromotionRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/service/PromotionService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#204 [25.03.13] 배포 테스트
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/controller/ChatWebSocketController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/CorsConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/WebSocketConfig.java
  CafeSync-FinalProject/src/main/resources/application.yml
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙
