Repository MNGFinal/CafeSync-Back, pull requests merged in 2025-02, with the labels that each got.

#5 [25.02.12] JWT 및 프론트 서버 연결 구현
  .github/ISSUE_TEMPLATE/backend_feature.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/issue_template.md
  CafeSync-FinalProject/build.gradle
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dao/UserRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/Role.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserDetailsImpl.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/User.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/TokenService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserDetailsServiceImpl.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/CorsConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/JWTUtil.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/JwtAuthenticationFilter.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/inventory/controller/InventoryController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/inventory/model/service/InvenService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/Controller.java
  CafeSync-FinalProject/src/main/resources/application.yml
Labels: ✅PR(Pull Request)✅

#6 [25.02.12] Basic -> main
  CafeSync-FinalProject/build.gradle
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dao/UserRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/Role.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserDetailsImpl.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/User.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/TokenService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserDetailsServiceImpl.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/CorsConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/JWTUtil.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/JwtAuthenticationFilter.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/inventory/controller/InventoryController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/inventory/model/service/InvenService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/Controller.java
  CafeSync-FinalProject/src/main/resources/application.yml
Labels: ✅PR(Pull Request)✅

#13 [25.02.13] API 호출 테스트
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dao/UserRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/EmployeeDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/FranchiseDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/JobDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserDetailsImpl.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserLoginDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Employee.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Franchise.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Job.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/User.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserDetailsServiceImpl.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranInvenDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/a.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#9 [25.02.12] JWT 토큰 로그인정보 추가
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dao/UserRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/EmployeeDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/FranchiseDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/JobDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserLoginDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Employee.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Franchise.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Job.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/User.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/a.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#14 [25.02.13] basic -> main
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dao/UserRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/EmployeeDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/FranchiseDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/JobDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserDetailsImpl.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserLoginDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Employee.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Franchise.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Job.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/User.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserDetailsServiceImpl.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranInvenDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/a.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#16 [25.02.13] 시큐리티 설정 일부 수정(임시)
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/JwtAuthenticationFilter.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#20 [25.02.13] FireBase 설정 및 API 호출 테스트, 시큐리티 설정 변경
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/firebase/FirebaseStorageService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/controller/MenuController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/service/MenuService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#21 [25.02.13] basic -> main
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/firebase/FirebaseStorageService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/controller/MenuController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/service/MenuService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#24 [25.02.14] 파이어베이스 및 시큐리티 로직 수정
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/CorsConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#25 [25.02.14] 아이디 찾기 로직 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/CorsConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/ScheduleController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dao/ScheduleRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dto/ScheduleDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Schedule.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/ScheduleService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/home/controller/FindController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/home/dao/AccountRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/home/dao/FranchiseRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/home/dto/AccountDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/home/dto/FranchiseDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/home/entity/Account.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/home/entity/Franchise.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/home/service/FindService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/dao/ScheduleRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/dto/ScheduleDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/entity/Schedule.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/service/ScheduleService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#28 백엔드 - [25.02.14] 바리스타노트 전체 조회
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/common/ResponseDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dao/NoteRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/NoteDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/a.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#34 [25.02.17] 재고조회 기능 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/common/ResponseDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranInvenDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InventoryDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/VendorDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/Inventory.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/Vendor.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dao/NoteRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/NoteDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/a.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#35 [25.02.17] basic -> main
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranInvenDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InventoryDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/VendorDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/Inventory.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/Vendor.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java
Labels: ✅PR(Pull Request)✅

#37 [25.02.17] 바리스타 노트 세부 조회 및 전체조회 재확인
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java
Labels: 🔙백엔드🔙

#40 [25.02.18] 재고 수량 업데이트 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#42 [25.02.18] 재고 데이터 삭제 기능 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#45 [25.02.18] basic -> main
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#47 [25.02.19] 가맹점 메뉴 조회 기능 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/controller/MenuController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/dao/MenuRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/entity/Menu.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/service/MenuService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#49 [25.02.19] 입출고 데이터 조회 기능 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/InOutRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranchiseDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutInventoryDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InventoryJoinDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/InOut.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/InOutService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#63 [25.02.19] 백엔드 합쳐놓기
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserLoginDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Franchise.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dto/EmployeeDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Employee.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/FranService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#64 [25.02.19]바리스타노트등록관련검증부분삭제
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserLoginDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Franchise.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dto/EmployeeDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Employee.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/FranService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java
Labels: 🔙백엔드🔙

#67 [25.02.20] 메뉴/가맹점코드수정
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/dto/FranDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/service/FranService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/controller/MenuController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/service/MenuService.java
Labels: 🔙백엔드🔙, 🛠️수정🛠️

#69 [25.02.20] 스케줄 관리 조회 수정
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/entity/Schedule.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/service/ScheduleService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙, 🛠️수정🛠️

#70 [25.02.20] 프랜차이즈 코드수정
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/FranService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
Labels: 🛠️수정🛠️

#72 [25.02.20] 입출고 승인 및 취소 로직 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInventoryRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/InOutInventoryRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/InOutRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInventory.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/InOutService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#75 [25.02.20] 발주 등록 기능 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/FranService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInventoryRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/InOutInventoryRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/InOutRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/OrderDetailRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/OrderRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDetailDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInventory.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/Order.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/OrderDetail.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/InOutService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/entity/Schedule.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/service/ScheduleService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#76 [25.02.20] basic -> main
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/OrderDetailRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/OrderRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDetailDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/Order.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/OrderDetail.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/InOutService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#77 [25.02.20] 프랜차이즈 이미지
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/dao/FranRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/dto/FranDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/entity/Fran.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/service/FranService.java
Labels: 🔙백엔드🔙

#84 [25.02.20] 스케줄 등록 로직 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/EmpController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dao/EmpRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/EmployeeService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/dto/ScheduleDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/entity/Schedule.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/service/ScheduleService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#97 [25.02.21] 가맹점 등록
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Employee.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/dto/FranDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/entity/Fran.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/service/FranService.java
Labels: 🔙백엔드🔙

#88 [2025-02-21] 바리스타 노트 삭제 기능
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/NoteDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/NoteInsertDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java
Labels: 🔙백엔드🔙

#89 [25.02.21] 발주 신청 조회, 스웨거 작성
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/OrderRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranInvenDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranchiseDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutInventoryDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutInventoryJoinDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutJoinDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InventoryDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InventoryJoinDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDetailDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/VendorDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#94 [25.02.21] 스웨거 명세 설정 및 리턴 타입 변경 작업
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
Labels: ✅PR(Pull Request)✅, 📢이슈📢, 🔙백엔드🔙, 🛠️수정🛠️

#105 [25.02.22] 전표 조회
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/VendorDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/SlipRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/ActDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/SlipDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/SummaryDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Slip.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/SlipService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/a.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#106 [25.02.23] 전표 추가 및 저장 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/controller/ActController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/dao/ActRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/dto/ActDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/entity/Act.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/service/ActService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/SlipInsertDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Slip.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/SlipService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/controller/SummaryController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/dao/SummaryRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/dto/SummaryDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/entity/Summary.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/service/SummaryService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/controller/VendorController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/dao/VendorRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/dto/VendorDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/entity/Vendor.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/service/VendorService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/service/a.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#107 [25.02.23] 전표 삭제 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/SlipRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/SlipService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#108 [25.02.23] 세금 및 손익계산서 생성 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/PnlRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/PnlSlipRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/TaxRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/PnlDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/PnlSlipDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/TaxDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Pnl.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/PnlSlip.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Tax.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/PnlService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/SlipService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/TaxService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#113 [25.02.24] 바리스타 조회수 기능
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/controller/ActController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/dao/ActRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/dto/ActDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/entity/Act.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/service/ActService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/OrderDetailRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/VendorDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/NoteDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/NoteInsertDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/NoteInsert.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/PnlRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/PnlSlipRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/SlipRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/TaxRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/ActDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/PnlDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/PnlSlipDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/SlipDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/SlipInsertDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/SummaryDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/TaxDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Pnl.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/PnlSlip.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Slip.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Tax.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/PnlService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/SlipService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/TaxService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/controller/SummaryController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/dao/SummaryRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/dto/SummaryDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/entity/Summary.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/service/SummaryService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/service/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/controller/Controller.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/controller/VendorController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/a.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/dao/VendorRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/dto/VendorDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/entity/Vendor.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/service/VendorService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/service/a.java
Labels: 🔙백엔드🔙

#120 [25.02.24] 가맹점 삭제
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
Labels: 🔙백엔드🔙

#122 [25.02.25] 세금 계산서 삭제
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Slip.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Tax.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/TaxService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/controller/TaxController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/model/dao/TaxRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/model/service/TaxService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#127 [25.02.25] basic -> main
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/common/ResponseDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/NoticeController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/service/NoticeService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/PnlRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/PnlSlipRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/SlipRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/PnlDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/PnlSlipDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Pnl.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/PnlSlip.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Slip.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Tax.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/PnlService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/SlipService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/TaxService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/controller/TaxController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/model/dao/TaxRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/model/service/TaxService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#129 [25.02.25] 스케줄 관리 수정
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/dao/ScheduleRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/entity/Schedule.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/service/ScheduleService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#134 [25.02.26] 공지사항등록
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/NoticeController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/dao/NoticeAccountRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/dao/NoticeInsertRepository.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/dto/NoticeInsertDTO.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/entity/NoticeInsert.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/service/NoticeService.java
Labels: 🔙백엔드🔙

#140 [25.02.27] 스케줄 수정 및 삭제 기능 구현
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/EmployeeService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/service/ScheduleService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙, 🛠️수정🛠️

#141 [25.02.27] 공지사항 수정/삭제/페이지네이션
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/NoteInsert.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/NoticeController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/entity/NoticeInsert.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/service/NoticeService.java
Labels: 🔙백엔드🔙

#145 [25.02.28] 본사메뉴삭제
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/service/FranService.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/controller/MenuController.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/entity/Menu.java
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/service/MenuService.java
Labels: ✅PR(Pull Request)✅, 🔙백엔드🔙

#149 [25.02.28] 스케줄 삭제 로직 복구
  CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
Labels: ✅PR(Pull Request)✅, 🐞버그🐞, 🔙백엔드🔙, 🛠️수정🛠️
